CREATE TABLE [dbo].[customerInfo](
	[customerId] [varchar](50) NOT NULL,
	[customerType] [varchar](1) NOT NULL,
	[customerName] [varchar](30) NOT NULL,
	[preferenceCall] [varchar](30) NOT NULL,
	[birthday] [varchar](50) NOT NULL,
	[gender] [varchar](1) NOT NULL,
	[country] [varchar](3) NOT NULL,
	[acenstralHome] [varchar](50) NULL,
	[residence] [varchar](250) NOT NULL,
	[address] [varchar](250) NOT NULL,
	[mobile] [varchar](30) NOT NULL,
	[phone1] [varchar](30) NULL,
	[phone2] [varchar](30) NULL,
	[email] [varchar](50) NULL,
	[occupation] [varchar](30) NULL,
	[companyType] [varchar](50) NULL,
	[mainBusiness] [varchar](250) NULL,
	[majorEcoSources] [varchar](250) NULL,
	[otherEcoSources] [varchar](250) NULL,
	[tabooMatters] [varchar](250) NULL,
	[referCustomer1] [varchar](50) NULL,
	[referCustomer2] [varchar](50) NULL,
	[referCustomer3] [varchar](50) NULL,
	[companyDescription] [varchar](500) NULL,
	[departmentId] [varchar](50) NOT NULL,
	[customerManagerId] [varchar](50) NOT NULL,
	[financialManagerId] [varchar](50) NOT NULL,
	[investmentAdviserId] [varchar](50) NOT NULL,
	[addDate] [varchar](50) NOT NULL,
	[modifyDate] [varchar](50) NOT NULL,
	[operatorName] [varchar](50) NOT NULL,
	[status] [varchar](50) NOT NULL,
	[registerSubmitDate] [varchar](50) NOT NULL,
	[businessId] [varchar](50) NOT NULL,
 CONSTRAINT [PK_customerInfo] PRIMARY KEY CLUSTERED 
(
	[customerId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]