package com.cmbc.pbms.bean;

// Generated 2015-5-4 16:45:24 by Hibernate Tools 3.4.0.CR1

/**
 * PbmsStruValueId generated by hbm2java
 */
public class PbmsStruValueId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5529251268688118080L;
	private String struId;
	private String term;

	public PbmsStruValueId() {
	}

	public PbmsStruValueId(String struId, String term) {
		this.struId = struId;
		this.term = term;
	}

	public String getStruId() {
		return this.struId;
	}

	public void setStruId(String struId) {
		this.struId = struId;
	}

	public String getTerm() {
		return this.term;
	}

	public void setTerm(String term) {
		this.term = term;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((struId == null) ? 0 : struId.hashCode());
		result = prime * result + ((term == null) ? 0 : term.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PbmsStruValueId other = (PbmsStruValueId) obj;
		if (struId == null) {
			if (other.struId != null)
				return false;
		} else if (!struId.equals(other.struId))
			return false;
		if (term == null) {
			if (other.term != null)
				return false;
		} else if (!term.equals(other.term))
			return false;
		return true;
	}



}
