package com.cmbc.pbms.bean;

// Generated 2015-5-4 16:45:24 by Hibernate Tools 3.4.0.CR1

/**
 * PbmsMenuInfo generated by hbm2java
 */
public class PbmsMenuInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7060764873126619237L;
	private int menuId;
	private String menuName;
	private Integer menuType;
	private Integer menuParent;
	private String menuLink;

	public PbmsMenuInfo() {
	}

	public PbmsMenuInfo(int menuId) {
		this.menuId = menuId;
	}

	public PbmsMenuInfo(int menuId, String menuName, Integer menuType,
			Integer menuParent, String menuLink) {
		this.menuId = menuId;
		this.menuName = menuName;
		this.menuType = menuType;
		this.menuParent = menuParent;
		this.menuLink = menuLink;
	}

	public int getMenuId() {
		return this.menuId;
	}

	public void setMenuId(int menuId) {
		this.menuId = menuId;
	}

	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	public Integer getMenuType() {
		return this.menuType;
	}

	public void setMenuType(Integer menuType) {
		this.menuType = menuType;
	}

	public Integer getMenuParent() {
		return this.menuParent;
	}

	public void setMenuParent(Integer menuParent) {
		this.menuParent = menuParent;
	}

	public String getMenuLink() {
		return this.menuLink;
	}

	public void setMenuLink(String menuLink) {
		this.menuLink = menuLink;
	}

}
