package com.cmbc.pbms.bean;

// Generated 2015-5-4 16:45:24 by Hibernate Tools 3.4.0.CR1

/**
 * PbmsRoleInfo generated by hbm2java
 */
public class PbmsRoleInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4406103291646018136L;
	private int roleId;
	private String roleName;
	private String authority;
	private String userId;
	private String alterTime;

	public PbmsRoleInfo() {
	}

	public PbmsRoleInfo(int roleId) {
		this.roleId = roleId;
	}

	public PbmsRoleInfo(int roleId, String roleName, String authority,
			String userId, String alterTime) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.authority = authority;
		this.userId = userId;
		this.alterTime = alterTime;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getAuthority() {
		return this.authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getAlterTime() {
		return this.alterTime;
	}

	public void setAlterTime(String alterTime) {
		this.alterTime = alterTime;
	}

}
