package com.cmbc.pbms.bean;

// Generated 2015-5-4 16:45:24 by Hibernate Tools 3.4.0.CR1

/**
 * PbmsDicInfoId generated by hbm2java
 */
public class PbmsDicInfoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2337422460473991144L;
	private int dicId;
	private int dicValue;

	public PbmsDicInfoId() {
	}

	public PbmsDicInfoId(int dicId, int dicValue) {
		this.dicId = dicId;
		this.dicValue = dicValue;
	}

	public int getDicId() {
		return this.dicId;
	}

	public void setDicId(int dicId) {
		this.dicId = dicId;
	}

	public int getDicValue() {
		return this.dicValue;
	}

	public void setDicValue(int dicValue) {
		this.dicValue = dicValue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PbmsDicInfoId))
			return false;
		PbmsDicInfoId castOther = (PbmsDicInfoId) other;

		return (this.getDicId() == castOther.getDicId())
				&& (this.getDicValue() == castOther.getDicValue());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDicId();
		result = 37 * result + this.getDicValue();
		return result;
	}

}
