package com.cmbc.pbms.bean;

// Generated 2015-5-4 16:45:24 by Hibernate Tools 3.4.0.CR1

/**
 * PbmsApproveInfo generated by hbm2java
 */
public class PbmsApproveInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5217660130672199070L;
	private int apprId;
	private Integer apprType;
	private Integer apprStatus;
	private Integer applyNo;
	private String applyUserId;
	private String curUserId;
	private String applyTime;
	private Integer apprStep;
	private String userId1;
	private String apprTime1;
	private Integer procResult1;
	private String remark1;
	private String userId2;
	private String apprTime2;
	private Integer procResult2;
	private String remark2;
	private String userId3;
	private String apprTime3;
	private Integer procResult3;
	private String remark3;
	private String userId4;
	private String apprTime4;
	private Integer procResult4;
	private String remark4;
	private String userId5;
	private String apprTime5;
	private Integer procResult5;
	private String remark5;
	private String apprCont;
	private String apprParam1;
	private String apprParam2;
	private String apprParam3;
	private String apprParam4;
	private String apprParam5;
	
	private String opt = "";

	public PbmsApproveInfo() {
	}

	public PbmsApproveInfo(int apprId) {
		this.apprId = apprId;
	}

	public PbmsApproveInfo(int apprId, Integer apprType, Integer apprStatus,
			Integer applyNo, String applyUserId, String curUserId,
			String applyTime, Integer apprStep, String userId1,
			String apprTime1, Integer procResult1, String remark1,
			String userId2, String apprTime2, Integer procResult2,
			String remark2, String userId3, String apprTime3,
			Integer procResult3, String remark3, String userId4,
			String apprTime4, Integer procResult4, String remark4,
			String userId5, String apprTime5, Integer procResult5,
			String remark5, String apprCont, String apprParam1,
			String apprParam2, String apprParam3, String apprParam4,
			String apprParam5) {
		this.apprId = apprId;
		this.apprType = apprType;
		this.apprStatus = apprStatus;
		this.applyNo = applyNo;
		this.applyUserId = applyUserId;
		this.curUserId = curUserId;
		this.applyTime = applyTime;
		this.apprStep = apprStep;
		this.userId1 = userId1;
		this.apprTime1 = apprTime1;
		this.procResult1 = procResult1;
		this.remark1 = remark1;
		this.userId2 = userId2;
		this.apprTime2 = apprTime2;
		this.procResult2 = procResult2;
		this.remark2 = remark2;
		this.userId3 = userId3;
		this.apprTime3 = apprTime3;
		this.procResult3 = procResult3;
		this.remark3 = remark3;
		this.userId4 = userId4;
		this.apprTime4 = apprTime4;
		this.procResult4 = procResult4;
		this.remark4 = remark4;
		this.userId5 = userId5;
		this.apprTime5 = apprTime5;
		this.procResult5 = procResult5;
		this.remark5 = remark5;
		this.apprCont = apprCont;
		this.apprParam1 = apprParam1;
		this.apprParam2 = apprParam2;
		this.apprParam3 = apprParam3;
		this.apprParam4 = apprParam4;
		this.apprParam5 = apprParam5;
	}

	public int getApprId() {
		return this.apprId;
	}

	public void setApprId(int apprId) {
		this.apprId = apprId;
	}

	public Integer getApprType() {
		return this.apprType;
	}

	public void setApprType(Integer apprType) {
		this.apprType = apprType;
	}

	public Integer getApprStatus() {
		return this.apprStatus;
	}

	public void setApprStatus(Integer apprStatus) {
		this.apprStatus = apprStatus;
	}

	public Integer getApplyNo() {
		return this.applyNo;
	}

	public void setApplyNo(Integer applyNo) {
		this.applyNo = applyNo;
	}

	public String getApplyUserId() {
		return this.applyUserId;
	}

	public void setApplyUserId(String applyUserId) {
		this.applyUserId = applyUserId;
	}

	public String getCurUserId() {
		return this.curUserId;
	}

	public void setCurUserId(String curUserId) {
		this.curUserId = curUserId;
	}

	public String getApplyTime() {
		return this.applyTime;
	}

	public void setApplyTime(String applyTime) {
		this.applyTime = applyTime;
	}

	public Integer getApprStep() {
		return this.apprStep;
	}

	public void setApprStep(Integer apprStep) {
		this.apprStep = apprStep;
	}

	public String getUserId1() {
		return this.userId1;
	}

	public void setUserId1(String userId1) {
		this.userId1 = userId1;
	}

	public String getApprTime1() {
		return this.apprTime1;
	}

	public void setApprTime1(String apprTime1) {
		this.apprTime1 = apprTime1;
	}

	public Integer getProcResult1() {
		return this.procResult1;
	}

	public void setProcResult1(Integer procResult1) {
		this.procResult1 = procResult1;
	}

	public String getRemark1() {
		return this.remark1;
	}

	public void setRemark1(String remark1) {
		this.remark1 = remark1;
	}

	public String getUserId2() {
		return this.userId2;
	}

	public void setUserId2(String userId2) {
		this.userId2 = userId2;
	}

	public String getApprTime2() {
		return this.apprTime2;
	}

	public void setApprTime2(String apprTime2) {
		this.apprTime2 = apprTime2;
	}

	public Integer getProcResult2() {
		return this.procResult2;
	}

	public void setProcResult2(Integer procResult2) {
		this.procResult2 = procResult2;
	}

	public String getRemark2() {
		return this.remark2;
	}

	public void setRemark2(String remark2) {
		this.remark2 = remark2;
	}

	public String getUserId3() {
		return this.userId3;
	}

	public void setUserId3(String userId3) {
		this.userId3 = userId3;
	}

	public String getApprTime3() {
		return this.apprTime3;
	}

	public void setApprTime3(String apprTime3) {
		this.apprTime3 = apprTime3;
	}

	public Integer getProcResult3() {
		return this.procResult3;
	}

	public void setProcResult3(Integer procResult3) {
		this.procResult3 = procResult3;
	}

	public String getRemark3() {
		return this.remark3;
	}

	public void setRemark3(String remark3) {
		this.remark3 = remark3;
	}

	public String getUserId4() {
		return this.userId4;
	}

	public void setUserId4(String userId4) {
		this.userId4 = userId4;
	}

	public String getApprTime4() {
		return this.apprTime4;
	}

	public void setApprTime4(String apprTime4) {
		this.apprTime4 = apprTime4;
	}

	public Integer getProcResult4() {
		return this.procResult4;
	}

	public void setProcResult4(Integer procResult4) {
		this.procResult4 = procResult4;
	}

	public String getRemark4() {
		return this.remark4;
	}

	public void setRemark4(String remark4) {
		this.remark4 = remark4;
	}

	public String getUserId5() {
		return this.userId5;
	}

	public void setUserId5(String userId5) {
		this.userId5 = userId5;
	}

	public String getApprTime5() {
		return this.apprTime5;
	}

	public void setApprTime5(String apprTime5) {
		this.apprTime5 = apprTime5;
	}

	public Integer getProcResult5() {
		return this.procResult5;
	}

	public void setProcResult5(Integer procResult5) {
		this.procResult5 = procResult5;
	}

	public String getRemark5() {
		return this.remark5;
	}

	public void setRemark5(String remark5) {
		this.remark5 = remark5;
	}

	public String getApprCont() {
		return this.apprCont;
	}

	public void setApprCont(String apprCont) {
		this.apprCont = apprCont;
	}

	public String getApprParam1() {
		return this.apprParam1;
	}

	public void setApprParam1(String apprParam1) {
		this.apprParam1 = apprParam1;
	}

	public String getApprParam2() {
		return this.apprParam2;
	}

	public void setApprParam2(String apprParam2) {
		this.apprParam2 = apprParam2;
	}

	public String getApprParam3() {
		return this.apprParam3;
	}

	public void setApprParam3(String apprParam3) {
		this.apprParam3 = apprParam3;
	}

	public String getApprParam4() {
		return this.apprParam4;
	}

	public void setApprParam4(String apprParam4) {
		this.apprParam4 = apprParam4;
	}

	public String getApprParam5() {
		return this.apprParam5;
	}

	public void setApprParam5(String apprParam5) {
		this.apprParam5 = apprParam5;
	}

	public String getOpt() {
		return opt;
	}

	public void setOpt(String opt) {
		this.opt = opt;
	}

}
