package com.cmbc.pbms.bean;

// Generated 2015-5-4 16:45:24 by Hibernate Tools 3.4.0.CR1

/**
 * PbmsStruValue generated by hbm2java
 */
public class PbmsStruValue implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7533479869337588637L;
	private PbmsStruValueId id;
	private Integer begValue;
	private Integer surpValue;
	private String alterTime;

	private String struName = "";
	
	public PbmsStruValue() {
	}

	public PbmsStruValue(PbmsStruValueId id) {
		this.id = id;
	}

	public PbmsStruValue(PbmsStruValueId id, Integer begValue,
			Integer surpValue, String alterTime) {
		this.id = id;
		this.begValue = begValue;
		this.surpValue = surpValue;
		this.alterTime = alterTime;
	}

	public PbmsStruValueId getId() {
		return this.id;
	}

	public void setId(PbmsStruValueId id) {
		this.id = id;
	}

	public Integer getBegValue() {
		return this.begValue;
	}

	public void setBegValue(Integer begValue) {
		this.begValue = begValue;
	}

	public Integer getSurpValue() {
		return this.surpValue;
	}

	public void setSurpValue(Integer surpValue) {
		this.surpValue = surpValue;
	}

	public String getAlterTime() {
		return this.alterTime;
	}

	public void setAlterTime(String alterTime) {
		this.alterTime = alterTime;
	}

	public String getStruId() {
		return id.getStruId();
	}

	public void setStruId(String struId) {
		this.id.setStruId(struId);
	}

	public String getTerm() {
		return this.id.getTerm();
	}

	public void setTerm(String term) {
		this.id.setTerm(term);
	}

	public String getStruName() {
		return struName;
	}

	public void setStruName(String struName) {
		this.struName = struName;
	}

	@Override
	public String toString() {
		return "PbmsStruValue [id=" + id + ", begValue=" + begValue
				+ ", surpValue=" + surpValue + ", alterTime=" + alterTime
				+ ", struName=" + struName + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PbmsStruValue other = (PbmsStruValue) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	
}
