package com.cmbc.pbms.bean;

// Generated 2015-5-4 16:45:24 by Hibernate Tools 3.4.0.CR1

/**
 * PbmsStruInfo generated by hbm2java
 */
public class PbmsStruInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4787462625245039594L;
	private String struId;
	private String struName;
	private String struAddr;
	private String struTel;
	private String alterTime;

	public PbmsStruInfo() {
	}

	public PbmsStruInfo(String struId) {
		this.struId = struId;
	}

	public PbmsStruInfo(String struId, String struName, String struAddr,
			String struTel, String alterTime) {
		this.struId = struId;
		this.struName = struName;
		this.struAddr = struAddr;
		this.struTel = struTel;
		this.alterTime = alterTime;
	}

	public String getStruId() {
		return this.struId;
	}

	public void setStruId(String struId) {
		this.struId = struId;
	}

	public String getStruName() {
		return this.struName;
	}

	public void setStruName(String struName) {
		this.struName = struName;
	}

	public String getStruAddr() {
		return this.struAddr;
	}

	public void setStruAddr(String struAddr) {
		this.struAddr = struAddr;
	}

	public String getStruTel() {
		return this.struTel;
	}

	public void setStruTel(String struTel) {
		this.struTel = struTel;
	}

	public String getAlterTime() {
		return this.alterTime;
	}

	public void setAlterTime(String alterTime) {
		this.alterTime = alterTime;
	}

}
