package com.cmbc.pbms.bean;

// Generated 2015-5-4 16:45:24 by Hibernate Tools 3.4.0.CR1

/**
 * PbmsStruValueId generated by hbm2java
 */
public class PbmsStruValueId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5529251268688118080L;
	private String struId;
	private String term;

	public PbmsStruValueId() {
	}

	public PbmsStruValueId(String struId, String term) {
		this.struId = struId;
		this.term = term;
	}

	public String getStruId() {
		return this.struId;
	}

	public void setStruId(String struId) {
		this.struId = struId;
	}

	public String getTerm() {
		return this.term;
	}

	public void setTerm(String term) {
		this.term = term;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PbmsStruValueId))
			return false;
		PbmsStruValueId castOther = (PbmsStruValueId) other;

		return ((this.getStruId() == castOther.getStruId()) || (this
				.getStruId() != null && castOther.getStruId() != null && this
				.getStruId().equals(castOther.getStruId())))
				&& ((this.getTerm() == castOther.getTerm()) || (this.getTerm() != null
						&& castOther.getTerm() != null && this.getTerm()
						.equals(castOther.getTerm())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getStruId() == null ? 0 : this.getStruId().hashCode());
		result = 37 * result
				+ (getTerm() == null ? 0 : this.getTerm().hashCode());
		return result;
	}

}
