package com.cmbc.pbms.bean;

// Generated 2015-5-4 16:45:24 by Hibernate Tools 3.4.0.CR1

/**
 * PbmsHospitalReg generated by hbm2java
 */
public class PbmsHospitalReg implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9096759447588718278L;
	private int seqNo;
	private String clientName;
	private String idcarNo;
	private Integer gender;
	private String servDate;
	private Integer hospital;
	private Integer medicalLabor;
	private String docter;
	private String illnessDes;

	public PbmsHospitalReg() {
	}

	public PbmsHospitalReg(int seqNo) {
		this.seqNo = seqNo;
	}

	public PbmsHospitalReg(int seqNo, String clientName, String idcarNo,
			Integer gender, String servDate, Integer hospital,
			Integer medicalLabor, String docter, String illnessDes) {
		this.seqNo = seqNo;
		this.clientName = clientName;
		this.idcarNo = idcarNo;
		this.gender = gender;
		this.servDate = servDate;
		this.hospital = hospital;
		this.medicalLabor = medicalLabor;
		this.docter = docter;
		this.illnessDes = illnessDes;
	}

	public int getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(int seqNo) {
		this.seqNo = seqNo;
	}

	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public String getIdcarNo() {
		return this.idcarNo;
	}

	public void setIdcarNo(String idcarNo) {
		this.idcarNo = idcarNo;
	}

	public Integer getGender() {
		return this.gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}

	public String getServDate() {
		return this.servDate;
	}

	public void setServDate(String servDate) {
		this.servDate = servDate;
	}

	public Integer getHospital() {
		return this.hospital;
	}

	public void setHospital(Integer hospital) {
		this.hospital = hospital;
	}

	public Integer getMedicalLabor() {
		return this.medicalLabor;
	}

	public void setMedicalLabor(Integer medicalLabor) {
		this.medicalLabor = medicalLabor;
	}

	public String getDocter() {
		return this.docter;
	}

	public void setDocter(String docter) {
		this.docter = docter;
	}

	public String getIllnessDes() {
		return this.illnessDes;
	}

	public void setIllnessDes(String illnessDes) {
		this.illnessDes = illnessDes;
	}

}
