package com.cmbc.pbms.bean;

// Generated 2015-5-4 16:45:24 by Hibernate Tools 3.4.0.CR1

/**
 * PbmsStruValue generated by hbm2java
 */
public class PbmsStruValue implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7533479869337588637L;
	private PbmsStruValueId id;
	private Integer begValue;
	private Integer surpValue;
	private String alterTime;

	private String struName = "";
	
	public PbmsStruValue() {
	}

	public PbmsStruValue(PbmsStruValueId id) {
		this.id = id;
	}

	public PbmsStruValue(PbmsStruValueId id, Integer begValue,
			Integer surpValue, String alterTime) {
		this.id = id;
		this.begValue = begValue;
		this.surpValue = surpValue;
		this.alterTime = alterTime;
	}

	public PbmsStruValueId getId() {
		return this.id;
	}

	public void setId(PbmsStruValueId id) {
		this.id = id;
	}

	public Integer getBegValue() {
		return this.begValue;
	}

	public void setBegValue(Integer begValue) {
		this.begValue = begValue;
	}

	public Integer getSurpValue() {
		return this.surpValue;
	}

	public void setSurpValue(Integer surpValue) {
		this.surpValue = surpValue;
	}

	public String getAlterTime() {
		return this.alterTime;
	}

	public void setAlterTime(String alterTime) {
		this.alterTime = alterTime;
	}

	public String getStruId() {
		return id.getStruId();
	}

	public void setStruId(String struId) {
		this.id.setStruId(struId);
	}

	public String getTerm() {
		return this.id.getTerm();
	}

	public void setTerm(String term) {
		this.id.setTerm(term);
	}

	public String getStruName() {
		return struName;
	}

	public void setStruName(String struName) {
		this.struName = struName;
	}

}
