package com.cmbc.pbms.bean;

// Generated 2015-5-4 16:45:24 by Hibernate Tools 3.4.0.CR1

/**
 * PbmsDicInfo generated by hbm2java
 */
public class PbmsDicInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3902037784312071196L;
	private PbmsDicInfoId id;
	private String dicName;
	private String dicCont;

	public PbmsDicInfo() {
	}

	public PbmsDicInfo(PbmsDicInfoId id) {
		this.id = id;
	}

	public PbmsDicInfo(PbmsDicInfoId id, String dicName, String dicCont) {
		this.id = id;
		this.dicName = dicName;
		this.dicCont = dicCont;
	}

	public PbmsDicInfoId getId() {
		return this.id;
	}

	public void setId(PbmsDicInfoId id) {
		this.id = id;
	}

	public String getDicName() {
		return this.dicName;
	}

	public void setDicName(String dicName) {
		this.dicName = dicName;
	}

	public String getDicCont() {
		return this.dicCont;
	}

	public void setDicCont(String dicCont) {
		this.dicCont = dicCont;
	}

}
